services:
  bob:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TOKEN=${TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - PIX_API_URL=${PIX_API_URL}
      - PIX_TOKEN=${PIX_TOKEN}
      - SERVER_MANAGER_URL=${SERVER_MANAGER_URL}
      - SERVER_MANAGER_TOKEN=${SERVER_MANAGER_TOKEN}

    deploy:

      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    restart: always
